### ISSUE TITLE
Runtime Error

### ISSUE THREAD

**Issue by jialinc1206** [YuelangX/AvatarMAV#5]
When running the train.py I got the following error:
(p3d) C:\Users\cyberarch12\Desktop\DHF23SS\AvatarMAV>python train.py
0it [00:01, ?it/s]
Traceback (most recent call last):
  File "train.py", line 44, in <module>
    trainer.train(0, 100)
  File "C:\Users\cyberarch12\Desktop\DHF23SS\AvatarMAV\lib\trainer\Trainer.py", line 35, in train
    data = self.camera(data, data['image'].shape[2])
  File "C:\Users\cyberarch12\anaconda3\envs\p3d\lib\site-packages\torch\nn\modules\module.py", line 1051, in _call_impl
    return forward_call(*input, **kwargs)
  File "C:\Users\cyberarch12\Desktop\DHF23SS\AvatarMAV\lib\module\NeuralCameraModule.py", line 211, in forward
    rays_o_grid, rays_d_grid = self.gen_part_rays(data['extrinsic'],
  File "C:\Users\cyberarch12\Desktop\DHF23SS\AvatarMAV\lib\module\NeuralCameraModule.py", line 26, in gen_part_rays
    trans = -torch.matmul(rot, extrinsic[:3, 3:])
RuntimeError: CUDA error: CUBLAS_STATUS_NOT_INITIALIZED when calling `cublasCreate(handle)`

Are there any possbile solutions for this error?
Thank you!

**Comment by jialinc1206** [comment]
For me, my computer memory was too full. Restarting the computer solved the problem.
